version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
environment:
  pfx_secret:
    secure: hdy14L35tr5KSz6ZCuPL9vons7DFlgo0dHo8gWYOkq8=
  pfx_salt:
    secure: KOz+2qEYja2tlD0D6s0+JddJZ7ATx52COlzIhn3/8Ax+UlaCrOOAytXV/UFuiRbkFc3p5DO2bZf5aOLFmcojrQ==
  pfx_password:
    secure: a4UPiwsKmU/zUH6zsReleHzCXG++ZwWimSoHu2xcjTo=
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: >-
      echo %pfx_secret% > pfx_secret.txt
      echo %pfx_salt% > pfx_salt.txt
      echo %pfx_password% > pfx_password.txt
  - ps: sleep 200
  - cmd: appveyor-tools\secure-file -decrypt DistroLauncher-Appx\GentooWSL.pfx.enc -secret %pfx_secret% -salt %pfx_salt%
  - ps: $password = ConvertTo-SecureString -String $env:pfx_password -Force -AsPlainText 
  - ps: Import-PfxCertificate -FilePath DistroLauncher-Appx\GentooWSL.pfx -CertStoreLocation Cert:\LocalMachine\My -Password $password
  
before_build:
  - ps: >-
      Invoke-WebRequest https://github.com/ThatWeirdAndrew/GentooWSL-FS/releases/latest/download/install.tar.gz -OutFile x64\install.tar.gz -UseBasicParsing
      $version='Version="' + $(Get-Date -Format "yy.MM.dd") + '.0"'
      $env:VERSIONDATE=$(Get-Date -Format "yy.MM.dd") + '.0'
      $file_contents = $(Get-Content .\DistroLauncher-Appx\MyDistro.appxmanifest) -replace 'Version="1.1.1.1"', $version
      $file_contents | Out-File "DistroLauncher-Appx\MyDistro.appxmanifest" -Encoding utf8
    
build_script:
- cmd: build.bat x64 rel
- ps: >-
    mkdir Artifacts
    copy "AppPackages\DistroLauncher-Appx\DistroLauncher-Appx_${ENV:VERSIONDATE}_Test\*.cer" Artifacts
    copy "AppPackages\DistroLauncher-Appx\DistroLauncher-Appx_${ENV:VERSIONDATE}_Test\*.appxbundle" Artifacts
    
artifacts:
- path: Artifacts\*.cer
  name: Certificate
- path: Artifacts\*.appxbundle
  name: Appx
  
deploy:
  tag: $(VERSIONDATE)
  description: 'GentooWSL!'
  provider: GitHub
  auth_token:
    secure: L3wYI3iXpq4EizAnmYB9VaGghyx39zOZtHWK4Ajsc4cvBiqKO0koeEYtun31EnBP
  artifact: Appx, Certificate
  on:
    branch: master                 # release from master branch only
