name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download Files
      run: |
        curl -s -o DistroLauncher-Appx\DistroLauncher-Appx_TemporaryKey.pfx ${{ secrets.FILE }}
        curl -o x64\install.tar.gz https://github.com/ThatWeirdAndrew/GentooWSL-FS/releases/latest/download/install.tar.gz
    - name: Change version based on date
      run: |
        FOR /F "tokens=* USEBACKQ" %g IN (`"C:\Program Files\Git\usr\bin\date.exe" +%y.%m.%d.0`) do (SET "VERSIONDATE=%g")
        "c:\Program Files\git\usr\bin\sed.exe" -i "s/[0-9]\.[0-9]\.[0-9]\.[0-9]/%VERSIONDATE%/g" DistroLauncher-Appx\MyDistro.appxmanifest
    - name: Build Appx
      run: |
        build.bat x64 rel
        mkdir Artifacts
        copy AppPackages\DistroLauncher-Appx\DistroLauncher-Appx_%VERSIONDATE%_Test\*.cer Artifacts
        copy AppPackages\DistroLauncher-Appx\DistroLauncher-Appx_%VERSIONDATE%_Test\*.appxbundle Artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Stuff
        path: Artifacts
        
